import { TransactionContext } from '../persistence/transaction';
import {
  CreateSequenceContactInput,
  SequenceContact,
  UpdateSequenceContactInput,
} from './sequence-contact.entity';

export interface SequenceContactFilter {
  companyId?: string;
  status?: string;
}

export interface SequenceContactRepository {
  findById(id: string): Promise<SequenceContact | null>;
  findBySequence(
    organizationId: string,
    sequenceId: string,
    filter?: SequenceContactFilter,
    ctx?: TransactionContext,
  ): Promise<SequenceContact[]>;
  findByContactAndSequence(sequenceId: string, contactId: string): Promise<SequenceContact | null>;
  /** Every sequence this contact is enrolled in, across the whole organization — needed by "No contactar" (§DO_NOT_CONTACT), which must stop every active sequence, not just the one the conversation belongs to. */
  findByContact(organizationId: string, contactId: string): Promise<SequenceContact[]>;
  /** Every contact row across every sequence in the org — the admin global monitoring panel's stats source, fetched once and grouped in-memory per sequence to avoid an N+1 call per row. */
  findAllByOrganization(organizationId: string): Promise<SequenceContact[]>;
  create(input: CreateSequenceContactInput, ctx?: TransactionContext): Promise<SequenceContact>;
  update(id: string, input: UpdateSequenceContactInput, ctx?: TransactionContext): Promise<SequenceContact>;
  /** Fase 2, Caso B/C — one statement for every contact enrolled in a batch, never one per row. Ids pre-generated by the caller. */
  createMany(
    inputs: Array<CreateSequenceContactInput & { id: string }>,
    ctx?: TransactionContext,
  ): Promise<SequenceContact[]>;
  /** Fase 2, Caso C — one statement to move every contact in the first-publish batch to SCHEDULED, never one UPDATE per contact. */
  bulkSetScheduled(
    updates: Array<{ sequenceContactId: string; nextScheduledAt: Date }>,
    ctx?: TransactionContext,
  ): Promise<void>;
  /** Fase 2, Caso D — atomic claim: succeeds (returns 1) only if the contact isn't already REMOVED; returns 0 otherwise (the caller must treat that as a conflict, never retry the write). */
  conditionalRemove(id: string, reason: string, ctx?: TransactionContext): Promise<number>;
  /** Fase 2, Caso E — one statement to remove every not-yet-removed contact of a company within one sequence, never one UPDATE per contact. Returns the number of rows actually changed. */
  bulkRemoveByCompany(
    organizationId: string,
    sequenceId: string,
    companyId: string,
    reason: string,
    ctx?: TransactionContext,
  ): Promise<number>;
  /** "Conversaciones de prueba" (QA) — hard delete, never soft-delete: only ever called on a synthetic, batch-scoped SequenceContact by DeleteSimulationConversationsUseCase. */
  delete(id: string, ctx?: TransactionContext): Promise<void>;
}
