import { TransactionContext } from '../persistence/transaction';
import {
  CreateScheduledEmailInput,
  ScheduledEmail,
  UpdateScheduledEmailInput,
} from './scheduled-email.entity';

export interface ScheduledEmailFilter {
  status?: string;
  sequenceContactId?: string;
  mailboxId?: string;
  batchId?: string;
  sequenceId?: string;
  companyId?: string;
}

export interface ScheduledEmailRepository {
  findById(id: string): Promise<ScheduledEmail | null>;
  findByIdempotencyKey(
    organizationId: string,
    idempotencyKey: string,
  ): Promise<ScheduledEmail | null>;
  findBySequenceContact(sequenceContactId: string): Promise<ScheduledEmail[]>;
  /** Fase 2, Caso C — one query for every contact in the first-publish batch, never one per contact. */
  findManyBySequenceContactIds(
    sequenceContactIds: string[],
    ctx?: TransactionContext,
  ): Promise<ScheduledEmail[]>;
  findAll(organizationId: string, filter?: ScheduledEmailFilter, ctx?: TransactionContext): Promise<ScheduledEmail[]>;
  create(input: CreateScheduledEmailInput, ctx?: TransactionContext): Promise<ScheduledEmail>;
  /** Fase 2, Caso C — one statement for the whole first-publish batch. Ids pre-generated by the caller. */
  createMany(
    inputs: Array<CreateScheduledEmailInput & { id: string }>,
    ctx?: TransactionContext,
  ): Promise<ScheduledEmail[]>;
  update(id: string, input: UpdateScheduledEmailInput): Promise<ScheduledEmail>;
  /** Fase 2, Caso D — one statement to cancel every not-yet-sent job for a single contact, never one per row. */
  cancelFutureForSequenceContact(
    sequenceContactId: string,
    reason: string,
    ctx?: TransactionContext,
  ): Promise<number>;
  /** Fase 2, Caso E — one statement to cancel every not-yet-sent job for every contact of a company within one sequence. */
  cancelFutureForSequenceCompany(
    sequenceId: string,
    companyId: string,
    reason: string,
    ctx?: TransactionContext,
  ): Promise<number>;
  /** Fase 2.1, §14 — one statement to cancel every not-yet-sent job for a mailbox being unlinked/revoked. Never touches already-sent/failed/cancelled rows. */
  cancelFutureForMailbox(mailboxId: string, reason: string, ctx?: TransactionContext): Promise<number>;
}
