import { ConflictException, Injectable } from '@nestjs/common';
import { Prisma, Contact as PrismaContactRow } from '@prisma/client';
import { Contact, CreateContactInput, UpdateContactInput } from '../../../domain/contact/contact.entity';
import { ContactRepository } from '../../../domain/contact/contact.repository';
import { TransactionContext } from '../../../domain/persistence/transaction';
import { PrismaService } from './prisma.service';
import { resolveClient } from './prisma-transaction-manager';

function toDomain(row: PrismaContactRow): Contact {
  return {
    id: row.id,
    organizationId: row.organizationId,
    clientId: row.clientId,
    companyId: row.companyId,
    email: row.email,
    firstName: row.firstName,
    lastName: row.lastName,
    fullName: row.fullName,
    jobTitle: row.jobTitle,
    phone: row.phone,
    city: row.city,
    country: row.country,
    website: row.website,
    linkedin: row.linkedin,
    customFields: row.customFields as Record<string, string>,
    suppressed: row.suppressed,
    suppressedAt: row.suppressedAt,
    suppressedReason: row.suppressedReason,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
    deletedAt: row.deletedAt,
  };
}

@Injectable()
export class PrismaContactRepository implements ContactRepository {
  constructor(private readonly prisma: PrismaService) {}

  async findById(id: string): Promise<Contact | null> {
    const row = await this.prisma.contact.findFirst({ where: { id, deletedAt: null } });
    return row ? toDomain(row) : null;
  }

  async findByEmail(organizationId: string, clientId: string, email: string): Promise<Contact | null> {
    const row = await this.prisma.contact.findFirst({
      where: { organizationId, clientId, email: { equals: email, mode: 'insensitive' }, deletedAt: null },
    });
    return row ? toDomain(row) : null;
  }

  async findByClient(organizationId: string, clientId: string): Promise<Contact[]> {
    const rows = await this.prisma.contact.findMany({ where: { organizationId, clientId, deletedAt: null } });
    return rows.map(toDomain);
  }

  async create(input: CreateContactInput): Promise<Contact> {
    try {
      const row = await this.prisma.contact.create({
        data: {
          organizationId: input.organizationId,
          clientId: input.clientId,
          companyId: input.companyId,
          email: input.email,
          firstName: input.firstName ?? null,
          lastName: input.lastName ?? null,
          fullName: input.fullName ?? null,
          jobTitle: input.jobTitle ?? null,
          phone: input.phone ?? null,
          city: input.city ?? null,
          country: input.country ?? null,
          website: input.website ?? null,
          linkedin: input.linkedin ?? null,
          customFields: (input.customFields ?? {}) as Prisma.InputJsonValue,
        },
      });
      return toDomain(row);
    } catch (error) {
      if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
        throw new ConflictException('A contact with this email already exists for this client.');
      }
      throw error;
    }
  }

  async update(id: string, input: UpdateContactInput, ctx?: TransactionContext): Promise<Contact> {
    const row = await resolveClient(this.prisma, ctx).contact.update({ where: { id }, data: input });
    return toDomain(row);
  }

  async findManyByEmails(
    organizationId: string,
    clientId: string,
    emails: string[],
    ctx?: TransactionContext,
  ): Promise<Contact[]> {
    if (emails.length === 0) return [];
    const rows = await resolveClient(this.prisma, ctx).contact.findMany({
      where: {
        organizationId,
        clientId,
        deletedAt: null,
        OR: emails.map((email) => ({ email: { equals: email, mode: 'insensitive' as const } })),
      },
    });
    return rows.map(toDomain);
  }

  async findManyByIds(ids: string[], ctx?: TransactionContext): Promise<Contact[]> {
    if (ids.length === 0) return [];
    const rows = await resolveClient(this.prisma, ctx).contact.findMany({
      where: { id: { in: ids }, deletedAt: null },
    });
    return rows.map(toDomain);
  }

  /** Fase 2, Caso B — one round trip for the whole batch of new contacts; ids pre-generated by the caller. */
  async createMany(inputs: Array<CreateContactInput & { id: string }>, ctx?: TransactionContext): Promise<Contact[]> {
    if (inputs.length === 0) return [];
    const client = resolveClient(this.prisma, ctx);
    const now = new Date();
    await client.contact.createMany({
      data: inputs.map((input) => ({
        id: input.id,
        organizationId: input.organizationId,
        clientId: input.clientId,
        companyId: input.companyId,
        email: input.email,
        firstName: input.firstName ?? null,
        lastName: input.lastName ?? null,
        fullName: input.fullName ?? null,
        jobTitle: input.jobTitle ?? null,
        phone: input.phone ?? null,
        city: input.city ?? null,
        country: input.country ?? null,
        website: input.website ?? null,
        linkedin: input.linkedin ?? null,
        customFields: (input.customFields ?? {}) as Prisma.InputJsonValue,
      })),
    });
    return inputs.map((input) => ({
      id: input.id,
      organizationId: input.organizationId,
      clientId: input.clientId,
      companyId: input.companyId,
      email: input.email,
      firstName: input.firstName ?? null,
      lastName: input.lastName ?? null,
      fullName: input.fullName ?? null,
      jobTitle: input.jobTitle ?? null,
      phone: input.phone ?? null,
      city: input.city ?? null,
      country: input.country ?? null,
      website: input.website ?? null,
      linkedin: input.linkedin ?? null,
      customFields: input.customFields ?? {},
      suppressed: false,
      suppressedAt: null,
      suppressedReason: null,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
    }));
  }
}
