import { ConflictException, Injectable } from '@nestjs/common';
import { Prisma, SequenceContact as PrismaSequenceContactRow } from '@prisma/client';
import {
  CreateSequenceContactInput,
  SequenceContact,
  UpdateSequenceContactInput,
} from '../../../domain/sequence-contact/sequence-contact.entity';
import {
  SequenceContactFilter,
  SequenceContactRepository,
} from '../../../domain/sequence-contact/sequence-contact.repository';
import { TransactionContext } from '../../../domain/persistence/transaction';
import { PrismaService } from './prisma.service';
import { resolveClient } from './prisma-transaction-manager';

function toDomain(row: PrismaSequenceContactRow): SequenceContact {
  return {
    id: row.id,
    organizationId: row.organizationId,
    clientId: row.clientId,
    sequenceId: row.sequenceId,
    sequenceVersion: row.sequenceVersion,
    contactId: row.contactId,
    companyId: row.companyId,
    sourceImportId: row.sourceImportId,
    assignedMailboxId: row.assignedMailboxId,
    assignedExecutiveId: row.assignedExecutiveId,
    currentStepId: row.currentStepId,
    currentStepPosition: row.currentStepPosition,
    status: row.status,
    nextScheduledAt: row.nextScheduledAt,
    startedAt: row.startedAt,
    lastSentAt: row.lastSentAt,
    repliedAt: row.repliedAt,
    completedAt: row.completedAt,
    stoppedAt: row.stoppedAt,
    stopReason: row.stopReason,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

@Injectable()
export class PrismaSequenceContactRepository implements SequenceContactRepository {
  constructor(private readonly prisma: PrismaService) {}

  async findById(id: string): Promise<SequenceContact | null> {
    const row = await this.prisma.sequenceContact.findUnique({ where: { id } });
    return row ? toDomain(row) : null;
  }

  async findBySequence(
    organizationId: string,
    sequenceId: string,
    filter: SequenceContactFilter = {},
    ctx?: TransactionContext,
  ): Promise<SequenceContact[]> {
    const where: Prisma.SequenceContactWhereInput = { organizationId, sequenceId };
    if (filter.companyId) where.companyId = filter.companyId;
    if (filter.status) where.status = filter.status as never;
    const rows = await resolveClient(this.prisma, ctx).sequenceContact.findMany({ where });
    return rows.map(toDomain);
  }

  async findByContactAndSequence(sequenceId: string, contactId: string): Promise<SequenceContact | null> {
    const row = await this.prisma.sequenceContact.findUnique({
      where: { sequenceId_contactId: { sequenceId, contactId } },
    });
    return row ? toDomain(row) : null;
  }

  async findByContact(organizationId: string, contactId: string): Promise<SequenceContact[]> {
    const rows = await this.prisma.sequenceContact.findMany({ where: { organizationId, contactId } });
    return rows.map(toDomain);
  }

  async findAllByOrganization(organizationId: string): Promise<SequenceContact[]> {
    const rows = await this.prisma.sequenceContact.findMany({ where: { organizationId } });
    return rows.map(toDomain);
  }

  async create(input: CreateSequenceContactInput, ctx?: TransactionContext): Promise<SequenceContact> {
    try {
      const row = await resolveClient(this.prisma, ctx).sequenceContact.create({
        data: {
          organizationId: input.organizationId,
          clientId: input.clientId,
          sequenceId: input.sequenceId,
          sequenceVersion: input.sequenceVersion,
          contactId: input.contactId,
          companyId: input.companyId,
          sourceImportId: input.sourceImportId ?? null,
          assignedMailboxId: input.assignedMailboxId,
          assignedExecutiveId: input.assignedExecutiveId,
          currentStepId: input.currentStepId,
          currentStepPosition: input.currentStepPosition,
        },
      });
      return toDomain(row);
    } catch (error) {
      if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2002') {
        throw new ConflictException('This contact is already enrolled in this sequence.');
      }
      throw error;
    }
  }

  async update(id: string, input: UpdateSequenceContactInput, ctx?: TransactionContext): Promise<SequenceContact> {
    const row = await resolveClient(this.prisma, ctx).sequenceContact.update({ where: { id }, data: input });
    return toDomain(row);
  }

  /** Fase 2, Caso B/C — one round trip for the whole batch; ids pre-generated by the caller. */
  async createMany(
    inputs: Array<CreateSequenceContactInput & { id: string }>,
    ctx?: TransactionContext,
  ): Promise<SequenceContact[]> {
    if (inputs.length === 0) return [];
    const client = resolveClient(this.prisma, ctx);
    const now = new Date();
    await client.sequenceContact.createMany({
      data: inputs.map((input) => ({
        id: input.id,
        organizationId: input.organizationId,
        clientId: input.clientId,
        sequenceId: input.sequenceId,
        sequenceVersion: input.sequenceVersion,
        contactId: input.contactId,
        companyId: input.companyId,
        sourceImportId: input.sourceImportId ?? null,
        assignedMailboxId: input.assignedMailboxId,
        assignedExecutiveId: input.assignedExecutiveId,
        currentStepId: input.currentStepId,
        currentStepPosition: input.currentStepPosition,
      })),
    });
    return inputs.map((input) => ({
      id: input.id,
      organizationId: input.organizationId,
      clientId: input.clientId,
      sequenceId: input.sequenceId,
      sequenceVersion: input.sequenceVersion,
      contactId: input.contactId,
      companyId: input.companyId,
      sourceImportId: input.sourceImportId ?? null,
      assignedMailboxId: input.assignedMailboxId,
      assignedExecutiveId: input.assignedExecutiveId,
      currentStepId: input.currentStepId,
      currentStepPosition: input.currentStepPosition,
      status: 'ACTIVE' as const,
      nextScheduledAt: null,
      startedAt: now,
      lastSentAt: null,
      repliedAt: null,
      completedAt: null,
      stoppedAt: null,
      stopReason: null,
      createdAt: now,
      updatedAt: now,
    }));
  }

  async conditionalRemove(id: string, reason: string, ctx?: TransactionContext): Promise<number> {
    const client = resolveClient(this.prisma, ctx);
    const result = await client.sequenceContact.updateMany({
      where: { id, status: { not: 'REMOVED' } },
      data: { status: 'REMOVED', stoppedAt: new Date(), stopReason: reason },
    });
    return result.count;
  }

  async bulkRemoveByCompany(
    organizationId: string,
    sequenceId: string,
    companyId: string,
    reason: string,
    ctx?: TransactionContext,
  ): Promise<number> {
    const client = resolveClient(this.prisma, ctx);
    const result = await client.sequenceContact.updateMany({
      where: { organizationId, sequenceId, companyId, status: { not: 'REMOVED' } },
      data: { status: 'REMOVED', stoppedAt: new Date(), stopReason: reason },
    });
    return result.count;
  }

  /** Fase 2, Caso C — one `UPDATE ... FROM (VALUES ...)` statement for the whole first-publish batch. */
  async bulkSetScheduled(
    updates: Array<{ sequenceContactId: string; nextScheduledAt: Date }>,
    ctx?: TransactionContext,
  ): Promise<void> {
    if (updates.length === 0) return;
    const client = resolveClient(this.prisma, ctx);
    const values = Prisma.join(
      updates.map(
        (u) => Prisma.sql`(${u.sequenceContactId}::text, ${u.nextScheduledAt}::timestamp)`,
      ),
    );
    await client.$executeRaw`
      UPDATE "sequence_contacts" AS c
      SET "status" = 'SCHEDULED', "nextScheduledAt" = v.next_scheduled_at, "updatedAt" = now()
      FROM (VALUES ${values}) AS v(contact_id, next_scheduled_at)
      WHERE c.id = v.contact_id
    `;
  }
}
