import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

/** §2/§3 — no `name`, `startAt`, `scheduledAt`, `requestedStartDate` or `requestedStartTime`: the executive never picks a start date/time, and the name is auto-generated by the backend only when "Iniciar gestión" actually submits the command. */
export class CreateSequenceExecutionDto {
  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  mailboxId!: string;

  @ApiProperty()
  @IsString()
  @IsNotEmpty()
  templateId!: string;
}
