import { ConflictException, Inject, Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { AggregateType, IntegrationCommand } from '../../domain/integration/integration-command.entity';
import { IntegrationCommandRepository } from '../../domain/integration/integration-command.repository';
import { TransactionContext } from '../../domain/persistence/transaction';
import { INTEGRATION_COMMAND_REPOSITORY } from '../../infrastructure/persistence/tokens';

/**
 * Fase 2 — centralizes the scope prefix used to namespace every
 * client-supplied `Idempotency-Key` header before it's stored, so the same
 * raw header value reused (by accident or by a buggy client) across two
 * different kinds of operations can never collide in the
 * `(organizationId, idempotencyKey)` uniqueness — `IntegrationCommand`
 * doesn't otherwise include commandType/aggregateType in that constraint.
 * Never build this string by hand anywhere else.
 */
export const IDEMPOTENCY_SCOPE = {
  MAILBOX_CONFIGURE: 'mailbox.configure',
  IMPORT_CONFIRM: 'import.confirm',
  SEQUENCE_PUBLISH: 'sequence.publish',
  SEQUENCE_CONTACT_REMOVE: 'sequence.contact.remove',
  SEQUENCE_COMPANY_REMOVE: 'sequence.company.remove',
  MAILBOX_LINK: 'mailbox.link',
  MAILBOX_REASSIGN_PRIMARY: 'mailbox.reassign_primary',
  MAILBOX_UNLINK: 'mailbox.unlink',
} as const;

export function buildIdempotencyStorageKey(scope: string, rawKey: string): string {
  return `${scope}:${rawKey}`;
}

export interface ClaimIdempotencyInput {
  organizationId: string;
  scope: string;
  rawIdempotencyKey: string;
  payloadHash: string;
  commandType: string;
  aggregateType: AggregateType;
  aggregateId: string;
  correlationId: string;
  requestedBy: string;
  /** The engine-facing payload — same shape every other command in this codebase already persists. Never secrets. */
  commandPayload: Record<string, unknown>;
  /**
   * Pre-generated by the caller (not by this service) — needed whenever
   * the resultSnapshot itself must embed the commandId (e.g. "the id of
   * the command this operation created"), which would otherwise not be
   * known until *after* this call returns. Defaults to a fresh `cmd_...`
   * id when omitted.
   */
  commandId?: string;
}

/**
 * Fase 2 — the single place every transactional use case goes through to
 * turn a client-supplied Idempotency-Key into a durable, race-safe claim.
 * Reuses `IntegrationCommand` as the persistent idempotency registry (see
 * Paso 2 migration proposal) — no parallel table.
 */
@Injectable()
export class IdempotentOperationService {
  constructor(
    @Inject(INTEGRATION_COMMAND_REPOSITORY) private readonly commands: IntegrationCommandRepository,
  ) {}

  /**
   * Call BEFORE opening the business transaction. If a command already
   * exists for this (organizationId, scoped key):
   *  - same payloadHash → returns it (caller replays its persisted result,
   *    never re-runs the business writes).
   *  - different payloadHash → throws 409, per §"Reutilización con otro payload".
   *  - none found → returns null (caller proceeds to validate + open the transaction).
   */
  async checkExisting(
    organizationId: string,
    scope: string,
    rawIdempotencyKey: string,
    payloadHash: string,
  ): Promise<IntegrationCommand | null> {
    const key = buildIdempotencyStorageKey(scope, rawIdempotencyKey);
    const existing = await this.commands.findByIdempotencyKey(organizationId, key);
    if (!existing) return null;
    if (existing.payloadHash !== payloadHash) {
      throw new ConflictException(
        'Esta Idempotency-Key ya fue utilizada con una solicitud distinta. Usa una clave nueva para una operación diferente.',
      );
    }
    return existing;
  }

  /**
   * Call as the LAST write inside the business transaction, once every
   * other write has succeeded. Persists the command row (status
   * REQUESTED, per §"Comando JSON dentro de la transacción") together
   * with the sanitized result to replay on a future retry. If a
   * concurrent request already won the race (unique-constraint conflict),
   * this throws — the whole transaction rolls back, and the caller must
   * call `checkExisting` again outside the transaction to recover the
   * winner's result.
   */
  async claim(
    ctx: TransactionContext,
    input: ClaimIdempotencyInput,
    resultSnapshot: Record<string, unknown>,
    httpStatusCode: number,
  ): Promise<IntegrationCommand> {
    const key = buildIdempotencyStorageKey(input.scope, input.rawIdempotencyKey);
    return this.commands.create(
      {
        organizationId: input.organizationId,
        commandId: input.commandId ?? `cmd_${randomUUID()}`,
        commandType: input.commandType as never,
        aggregateType: input.aggregateType,
        aggregateId: input.aggregateId,
        schemaVersion: '1.0',
        idempotencyKey: key,
        correlationId: input.correlationId,
        payload: input.commandPayload,
        requestedBy: input.requestedBy,
        payloadHash: input.payloadHash,
        resultSnapshot,
        httpStatusCode,
      },
      ctx,
    );
  }

  /**
   * Fase 2.1 — for commands that have no post-commit engine dispatch step
   * (e.g. MAILBOX_LINK_REQUESTED, whose external call already happened,
   * successfully, before the transaction opened): marks the durable record
   * COMPLETED inside the SAME transaction as the rest of the business
   * writes, since there is no pending async work left to represent.
   */
  async markCompleted(commandRowId: string, ctx?: TransactionContext): Promise<void> {
    await this.commands.update(commandRowId, { status: 'COMPLETED', completedAt: new Date() }, ctx);
  }

  /**
   * Best-effort, non-transactional refresh of the persisted resultSnapshot
   * — called strictly *after* commit, once the post-commit dispatch to the
   * (simulated) port is known to have succeeded or failed, so a future
   * idempotent retry sees the same commandStatus the original caller did
   * (rather than the frozen "REQUESTED" captured at claim() time, before
   * dispatch). Never re-opens the business transaction; a failure here is
   * logged by the caller and never surfaces as an HTTP error — the
   * business operation already committed regardless.
   */
  async refreshResultSnapshot(commandRowId: string, resultSnapshot: Record<string, unknown>): Promise<void> {
    await this.commands.update(commandRowId, { resultSnapshot });
  }
}
