/**
 * Fase Firma — one row per uploaded signature image. Never stores the
 * binary itself (that lives in the storage adapter, local disk in
 * `simulated` mode or the R2 bucket in `r2` mode) — this is purely the
 * ownership/traceability/orphan-detection record §7 asks for.
 *
 * AVAILABLE: uploaded, not yet known to be used anywhere.
 * REFERENCED: appears in at least one template's current signatureHtml or
 * in an already-published SequenceTemplateVersion's frozen snapshot —
 * never eligible for physical deletion while in this state.
 * ORPHANED: was AVAILABLE, never got referenced, and is older than the
 * cleanup threshold (§13) — eligible for physical deletion, not deleted
 * automatically.
 * DELETED: physically removed from storage; the row is kept for audit.
 */
export type SignatureAssetStatus = 'AVAILABLE' | 'REFERENCED' | 'ORPHANED' | 'DELETED';

export interface SignatureAsset {
  id: string;
  organizationId: string;
  ownerUserId: string;
  /** Fase 2 (R2), §4 — nullable only for rows uploaded before this column existed; every upload from now on always sets it. */
  mailboxId: string | null;
  /** Immutable — `firmas/{correo-normalizado}/{id}.{extension}` (Fase 2, R2). Never reused across uploads. */
  objectKey: string;
  publicUrl: string;
  contentType: 'image/png' | 'image/jpeg' | 'image/gif';
  /** Sanitized (no path separators, no original directory) — kept only for display. */
  originalFileName: string;
  sizeBytes: number;
  width: number;
  height: number;
  sha256: string;
  status: SignatureAssetStatus;
  createdAt: Date;
  deletedAt: Date | null;
}

export interface CreateSignatureAssetInput {
  /** Pre-generated by the caller — must equal the `{assetId}` embedded in `objectKey`, so the storage object and the tracking row always share one identity. */
  id: string;
  organizationId: string;
  ownerUserId: string;
  mailboxId: string;
  objectKey: string;
  publicUrl: string;
  contentType: 'image/png' | 'image/jpeg' | 'image/gif';
  originalFileName: string;
  sizeBytes: number;
  width: number;
  height: number;
  sha256: string;
}

export interface UpdateSignatureAssetInput {
  status?: SignatureAssetStatus;
  deletedAt?: Date | null;
}
