export const ORGANIZATION_REPOSITORY = Symbol('ORGANIZATION_REPOSITORY');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const USER_ROLE_REPOSITORY = Symbol('USER_ROLE_REPOSITORY');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const MAILBOX_REPOSITORY = Symbol('MAILBOX_REPOSITORY');
export const MAILBOX_CONNECTION_TEST_REPOSITORY = Symbol('MAILBOX_CONNECTION_TEST_REPOSITORY');
export const MAILBOX_ASSIGNMENT_REPOSITORY = Symbol('MAILBOX_ASSIGNMENT_REPOSITORY');
export const TEMPLATE_REPOSITORY = Symbol('TEMPLATE_REPOSITORY');
export const VARIABLE_REPOSITORY = Symbol('VARIABLE_REPOSITORY');
export const SIGNATURE_REPOSITORY = Symbol('SIGNATURE_REPOSITORY');
export const SIGNATURE_VERSION_REPOSITORY = Symbol('SIGNATURE_VERSION_REPOSITORY');
export const SEQUENCE_REPOSITORY = Symbol('SEQUENCE_REPOSITORY');
export const SEQUENCE_STEP_REPOSITORY = Symbol('SEQUENCE_STEP_REPOSITORY');
export const SEQUENCE_STEP_VERSION_REPOSITORY = Symbol('SEQUENCE_STEP_VERSION_REPOSITORY');
export const MANAGED_CLIENT_REPOSITORY = Symbol('MANAGED_CLIENT_REPOSITORY');
export const CLIENT_EXECUTIVE_ASSIGNMENT_REPOSITORY = Symbol(
  'CLIENT_EXECUTIVE_ASSIGNMENT_REPOSITORY',
);
export const DOMAIN_REPOSITORY = Symbol('DOMAIN_REPOSITORY');
export const CONVERSATION_REPOSITORY = Symbol('CONVERSATION_REPOSITORY');
export const CONVERSATION_MESSAGE_REPOSITORY = Symbol('CONVERSATION_MESSAGE_REPOSITORY');
export const CONVERSATION_TAG_REPOSITORY = Symbol('CONVERSATION_TAG_REPOSITORY');
export const CONVERSATION_NOTE_REPOSITORY = Symbol('CONVERSATION_NOTE_REPOSITORY');
export const CONVERSATION_READ_STATE_REPOSITORY = Symbol('CONVERSATION_READ_STATE_REPOSITORY');
export const INTEGRATION_COMMAND_REPOSITORY = Symbol('INTEGRATION_COMMAND_REPOSITORY');
export const INTEGRATION_EVENT_REPOSITORY = Symbol('INTEGRATION_EVENT_REPOSITORY');
export const COMPANY_REPOSITORY = Symbol('COMPANY_REPOSITORY');
export const CONTACT_REPOSITORY = Symbol('CONTACT_REPOSITORY');
export const SEQUENCE_IMPORT_REPOSITORY = Symbol('SEQUENCE_IMPORT_REPOSITORY');
export const SEQUENCE_IMPORT_ROW_REPOSITORY = Symbol('SEQUENCE_IMPORT_ROW_REPOSITORY');
export const SEQUENCE_CONTACT_REPOSITORY = Symbol('SEQUENCE_CONTACT_REPOSITORY');
export const SCHEDULED_EMAIL_REPOSITORY = Symbol('SCHEDULED_EMAIL_REPOSITORY');
export const SEQUENCE_TEMPLATE_REPOSITORY = Symbol('SEQUENCE_TEMPLATE_REPOSITORY');
export const SEQUENCE_TEMPLATE_STEP_REPOSITORY = Symbol('SEQUENCE_TEMPLATE_STEP_REPOSITORY');
export const SEQUENCE_TEMPLATE_VERSION_REPOSITORY = Symbol('SEQUENCE_TEMPLATE_VERSION_REPOSITORY');
export const SEQUENCE_EXECUTION_REPOSITORY = Symbol('SEQUENCE_EXECUTION_REPOSITORY');
export const PROSPECT_IMPORT_REPOSITORY = Symbol('PROSPECT_IMPORT_REPOSITORY');
export const PROSPECT_IMPORT_ROW_REPOSITORY = Symbol('PROSPECT_IMPORT_ROW_REPOSITORY');
export const SIGNATURE_ASSET_REPOSITORY = Symbol('SIGNATURE_ASSET_REPOSITORY');
export const EMAIL_BODY_ASSET_REPOSITORY = Symbol('EMAIL_BODY_ASSET_REPOSITORY');

/**
 * Internal to the persistence layer — resolves to a live PrismaService
 * when PERSISTENCE_DRIVER=postgres and to `null` otherwise. Only
 * PersistenceModule and PersistenceHealthIndicator should ever inject
 * this; everything else depends on the repository tokens above.
 */
export const PRISMA_SERVICE = Symbol('PRISMA_SERVICE');

/** Fase 2 — Unit of Work. See domain/persistence/transaction.ts. */
export const TRANSACTION_MANAGER = Symbol('TRANSACTION_MANAGER');
