/**
 * Fase 2 (R2), §7 — one row per image uploaded into a Plantilla step's
 * body HTML. Deliberately its own type/table, never merged with
 * SignatureAsset — a body image belongs to the organization/uploader, not
 * to a mailbox, and lives under its own `email-body/` prefix, never mixed
 * with `firmas/`.
 *
 * AVAILABLE: uploaded, not yet known to be used anywhere.
 * REFERENCED: appears in at least one step's current bodyHtml draft or in
 * an already-published SequenceTemplateVersion's frozen step snapshot.
 * ORPHANED: was AVAILABLE, never got referenced, older than the cleanup
 * threshold — eligible for physical deletion, never deleted automatically.
 * DELETED: physically removed from storage; the row is kept for audit.
 */
export type EmailBodyAssetStatus = 'AVAILABLE' | 'REFERENCED' | 'ORPHANED' | 'DELETED';

export interface EmailBodyAsset {
  id: string;
  organizationId: string;
  ownerUserId: string;
  /** Immutable — `email-body/{organizationId}/{ownerUserId}/{id}.{extension}`. Never reused across uploads. */
  objectKey: string;
  publicUrl: string;
  contentType: 'image/png' | 'image/jpeg' | 'image/gif';
  originalFileName: string;
  sizeBytes: number;
  width: number;
  height: number;
  sha256: string;
  status: EmailBodyAssetStatus;
  createdAt: Date;
  deletedAt: Date | null;
}

export interface CreateEmailBodyAssetInput {
  /** Pre-generated by the caller — must equal the `{assetId}` embedded in `objectKey`. */
  id: string;
  organizationId: string;
  ownerUserId: string;
  objectKey: string;
  publicUrl: string;
  contentType: 'image/png' | 'image/jpeg' | 'image/gif';
  originalFileName: string;
  sizeBytes: number;
  width: number;
  height: number;
  sha256: string;
}

export interface UpdateEmailBodyAssetInput {
  status?: EmailBodyAssetStatus;
  deletedAt?: Date | null;
}
