import { TransactionContext } from '../persistence/transaction';
import { Contact, CreateContactInput, UpdateContactInput } from './contact.entity';

export interface ContactRepository {
  findById(id: string): Promise<Contact | null>;
  /** Dedup scope is (organization, client, email) — the same prospect can legitimately exist under two different managed clients. */
  findByEmail(organizationId: string, clientId: string, email: string): Promise<Contact | null>;
  findByClient(organizationId: string, clientId: string): Promise<Contact[]>;
  create(input: CreateContactInput): Promise<Contact>;
  update(id: string, input: UpdateContactInput, ctx?: TransactionContext): Promise<Contact>;
  /** Fase 2, Caso B — one query for every distinct email in a batch, never one per row. */
  findManyByEmails(
    organizationId: string,
    clientId: string,
    emails: string[],
    ctx?: TransactionContext,
  ): Promise<Contact[]>;
  /** Ids are pre-generated by the caller so the result can be used immediately without a re-read. */
  createMany(inputs: Array<CreateContactInput & { id: string }>, ctx?: TransactionContext): Promise<Contact[]>;
  /** Fase 2, Caso C — one query to resolve every contact enrolled in a sequence, never one per row. */
  findManyByIds(ids: string[], ctx?: TransactionContext): Promise<Contact[]>;
  /** "Conversaciones de prueba" (QA) — hard delete, never soft-delete: only ever called on a synthetic, batch-scoped Contact by DeleteSimulationConversationsUseCase. */
  delete(id: string, ctx?: TransactionContext): Promise<void>;
}
