import { TransactionContext } from '../persistence/transaction';
import { Company, CreateCompanyInput, UpdateCompanyInput } from './company.entity';

export interface CompanyRepository {
  findById(id: string): Promise<Company | null>;
  findByNormalizedName(
    organizationId: string,
    clientId: string,
    normalizedName: string,
  ): Promise<Company | null>;
  findByClient(organizationId: string, clientId: string): Promise<Company[]>;
  create(input: CreateCompanyInput): Promise<Company>;
  update(id: string, input: UpdateCompanyInput): Promise<Company>;
  /** Fase 2, Caso B — one query for every distinct company name in a batch, never one per row. */
  findManyByNormalizedNames(
    organizationId: string,
    clientId: string,
    normalizedNames: string[],
    ctx?: TransactionContext,
  ): Promise<Company[]>;
  /** Fase 2, Caso C — one query to resolve every company referenced by a sequence's enrolled contacts, never one per row. */
  findManyByIds(ids: string[], ctx?: TransactionContext): Promise<Company[]>;
  /** Ids are pre-generated by the caller so the result can be used immediately without a re-read (createMany doesn't return rows in Prisma). */
  createMany(inputs: Array<CreateCompanyInput & { id: string }>, ctx?: TransactionContext): Promise<Company[]>;
  /** "Conversaciones de prueba" (QA) — hard delete, never soft-delete: only ever called on the synthetic, batch-scoped Company by DeleteSimulationConversationsUseCase. */
  delete(id: string, ctx?: TransactionContext): Promise<void>;
}
